minimumReleaseAgeExclude:
  - pako@2.2.0

shellEmulator: true

# eslint-disable-next-line pnpm/yaml-enforce-settings, yaml/plain-scalar
trustPolicy: 'off'

packages:
  - playground
  - tauri

allowBuilds:
  esbuild: true
